First cut
mesosphere/d2iq-engineering-blog pull request #47
Opened 2022-11-17 08:45 UTC by arbhoj

2023-01-12 10:59 UTC, jimmidyson requested changes
Sorry I didn't realise this post wasn't finished when I started reviewing. I'm going to mark it as a draft PR to indicate that now. Please set it back to ready for review when it's ready.

2023-01-12 10:59 UTC, jimmidyson commented on content/posts/f5-k8s-lb-svc/index.md
> +excerpt: Learn how to configure a kubernetes cluster to provision a service of type LoadBalancer with F5 BIG-IP
```suggestion
excerpt: Learn how to configure a Kubernetes cluster to provision a service of type LoadBalancer with F5 BIG-IP 
```

2023-01-12 10:59 UTC, jimmidyson commented on content/posts/f5-k8s-lb-svc/index.md
> +# Options to provision LoadBalancer Services in an on-premise Kubernetes Cluster
```suggestion
# Options to provision LoadBalancer Services in an on-premise Kubernetes cluster
```

2023-01-12 10:59 UTC, jimmidyson commented on content/posts/f5-k8s-lb-svc/index.md
> +When deploying Kubernetes clusters in the cloud (AWS, Azure, GCP etc.) a Kubernetes service of type [LoadBalancer](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer) is by
```suggestion
When deploying Kubernetes clusters in the cloud (AWS, Azure, GCP etc.) a Kubernetes service of type [LoadBalancer](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer) is by default provisioned automatically by the appropriate [cloud controller manager](https://kubernetes.io/docs/concepts/architecture/cloud-controller/) using the native load-balancer service (e.g. [ELB](https://aws.amazon.com/elasticloadbalancing/) on AWS). It's not the same for on-premise clusters, which require additional components to be deployed/configured to get this functionality. There are a few Kubernetes native options like [metallb](https://metallb.universe.tf/) and [kube-vip](https://kube-vip.io/). However, for production clusters and clusters that process heavy traffic, an external load-balancer might be a better choice. [F5 BIG-IP LTM](https://www.f5.com/products/big-ip-services/local-traffic-manager) is one of the most widely used load-balancers in the industry today and the best thing is that it integrates really nicely with Kubernetes. 
```

2023-01-12 10:59 UTC, jimmidyson commented on content/posts/f5-k8s-lb-svc/index.md
> +In this blog we will see how to configure an on-premise Kubernetes cluster to integrate with [F5 BIG-IP LTM](https://www.f5.com/products/big-ip-services/local-traffic-manager) to provision a service
```suggestion
In this blog we will see how to configure an on-premise Kubernetes cluster to integrate with [F5 BIG-IP LTM](https://www.f5.com/products/big-ip-services/local-traffic-manager) to provision a service of type `LoadBalancer`.
```

2023-01-12 10:59 UTC, jimmidyson commented on content/posts/f5-k8s-lb-svc/index.md
> +7. This uses `docker.io/f5networks/f5-ipam-controller:0.1.5` & `docker.io/f5networks/k8s-bigip-ctlr:2.9.1` images. Download, retag and push the images to a local registry and change the deployment sp
Can you please add links to the different components here? I don't know what they are and not every reader will either so linking would help the reader.

2023-01-12 10:59 UTC, jimmidyson commented on content/posts/f5-k8s-lb-svc/index.md
> +>- BIG-IP-CTLR: 2.9.1
```suggestion
This blog used the following versions to test:

* BIG-IP: 16.1.3.1 Build 0.0.11 Point Release 1
* AS3: v3.39.0
* BIG-IP-CTLR: 2.9.1
```

2023-01-12 10:59 UTC, jimmidyson commented on content/posts/f5-k8s-lb-svc/index.md
> +## Steps to Integrate a Kuberntes Cluster with F5 BIG-IP
```suggestion
## Steps to Integrate a Kuberntes cluster with F5 BIG-IP
```

2023-01-12 10:59 UTC, jimmidyson commented on content/posts/f5-k8s-lb-svc/index.md
> +There are two options based on whether F5 controllers are to be directly deployed to the target cluster or deployed via ClusterResourceSets for a CAPI provisioned cluster either at cluter creation ti
```suggestion
There are two options based on whether F5 controllers are to be directly deployed to the target cluster, or deployed via [`ClusterResourceSets`](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-resource-set.html) for a [CAPI](https://cluster-api.sigs.k8s.io/) provisioned cluster either at cluster creation time or after the cluster has been deployed.
```

2023-03-17 22:50 UTC, arbhoj commented
Accepted review comments and added the required links in the requirements section

2023-03-17 22:58 UTC, arbhoj commented
Merging

2023-03-20 13:12 UTC, tillt reviewed
Looks great to me.

Just learned that we will need to find a nice picture representing this post graphically. Checking the offerings of https://unsplash.com/ following @jimmidyson nice suggestion.

2023-03-20 13:12 UTC, tillt commented on content/posts/f5-k8s-lb-svc/index.md
> +<br/>
Do we really need those? Lemme assume we don't and suggest changes...

2023-03-20 13:12 UTC, tillt commented on content/posts/f5-k8s-lb-svc/index.md
> +<br/>
```suggestion

```

2023-03-20 13:12 UTC, tillt commented on content/posts/f5-k8s-lb-svc/index.md
> +<br/>
```suggestion

```

2023-03-20 13:12 UTC, tillt commented on content/posts/f5-k8s-lb-svc/index.md
> +<br/>
```suggestion

```

2023-03-20 13:12 UTC, tillt commented on content/posts/f5-k8s-lb-svc/index.md
> +<br/>
```suggestion

```

2023-03-20 13:12 UTC, tillt commented on content/posts/f5-k8s-lb-svc/index.md
> +<br/>
```suggestion

```

2023-03-20 15:09 UTC, jimmidyson commented
Rebased...

2023-03-20 15:21 UTC, jimmidyson approved these changes

2023-03-23 22:27 UTC, tillt approved these changes

2023-03-23 22:28 UTC, tillt submitted a review, later dismissed

2023-03-23 23:21 UTC, tillt submitted a review, later dismissed

2023-03-29 19:49 UTC, vacas5 submitted a review, later dismissed

2023-03-29 19:52 UTC, tillt approved these changes

2023-03-29 20:03 UTC, tillt commented
The preview keeps showing the last article from Kim-Norman - that is confusing. @jimmidyson any idea?

2023-03-29 20:06 UTC, merged