Use ChatGPT to write an infrastructure provider
mesosphere/d2iq-engineering-blog pull request #59
Opened 2023-03-08 20:40 UTC by dkoshkin

A fun post on how to use ChatGPT to write an infrastructure provider

2023-03-08 21:24 UTC, mmcelroy91 reviewed
Dang, I'm out of a job! 
![image](https://user-images.githubusercontent.com/102097392/223853169-4fd082fc-a112-436a-ace8-ea4449f17090.png)
This was definitely interesting... maybe little bot dude can help me write better "steps" when following behind code.  Definitely interested to see how the technology evolves in the future!

2023-03-08 21:25 UTC, mmcelroy91 approved these changes

2023-03-08 21:26 UTC, cmastr commented on content/posts/chatgpt-writes-a-capi-infrastructure-provider/index.md
> +But, besides the initial novelty of getting it to write romantic texts to send to my wife or bad jokes to send to my friends, I haven't used very much after that.
```suggestion
But, besides the initial novelty of getting it to write romantic texts to send to my wife or bad jokes to send to my friends, I haven't used it very much after that.
```

2023-03-13 12:49 UTC, tillt submitted a review, later dismissed
Love it a lot -- what a great post.

I refrained from nit-picking on "I'm" etc as this post is very personal language centred and that fits the theme to me very well.

2023-03-13 14:06 UTC, jimmidyson requested changes

2023-03-13 14:06 UTC, jimmidyson commented on content/posts/chatgpt-writes-a-capi-infrastructure-provider/index.md
> +there are some required fields that are missing, let's see if ChatGTP can figure those out for us:
```suggestion
there are some required fields that are missing, let's see if ChatGPT can figure those out for us:
```

2023-03-13 17:17 UTC, msdolbey commented on content/posts/chatgpt-writes-a-capi-infrastructure-provider/index.md
> +As a software engineer I got curious again and decided to find out if ChatGPT can help do my job (without it trying to break up my marriage in the process).
```suggestion
As a software engineer, I got curious again and decided to find out if ChatGPT can help do my job (without it trying to break up my marriage in the process).
```

2023-03-13 17:19 UTC, msdolbey commented on content/posts/chatgpt-writes-a-capi-infrastructure-provider/index.md
> +We are on the right track, it knows that it needs to use [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) and something about a "Cluster".
Love this line

2023-03-13 17:20 UTC, msdolbey commented on content/posts/chatgpt-writes-a-capi-infrastructure-provider/index.md
> +It even generated some (incomplete) boilerplate Go code for us. (not shown for sake of brevity)
Just period at the end of this line so the parenthetical statement isn't hanging.

```suggestion
It even generated some (incomplete) boilerplate Go code for us (not shown for sake of brevity).
```

2023-03-13 17:23 UTC, msdolbey commented on content/posts/chatgpt-writes-a-capi-infrastructure-provider/index.md
> +At this point, ChatGPT provider a lot of boilerplate code, let's try it to use what the context it has through our interaction
```suggestion
At this point, ChatGPT provided a lot of boilerplate code, let's try it to use what the context it has through our interaction
```

2023-03-13 17:25 UTC, msdolbey commented on content/posts/chatgpt-writes-a-capi-infrastructure-provider/index.md
> +At this point, ChatGPT has given us lots of useful information, sure, we can't just copy and paste the code and have it work, but it's great starting point!
Just a nit - I don't know if it needs to be two different sentences, but I like it this way.

```suggestion
At this point, ChatGPT has given us lots of useful information. Sure, we can't just copy and paste the code and have it work, but it's great starting point!
```

2023-03-13 17:29 UTC, msdolbey submitted a review, later dismissed
👍 

Some small nits, but overall - great post. A little shocking and horrifying that ... I mean, I have a CKA and chatgpt is like ... challenging me here ... 

![side eye at you chatgpt](https://media.tenor.com/rWGDKxR6RvAAAAAd/kent-brockman-insect-overlords.gif)

2023-03-15 16:55 UTC, tillt approved these changes
Awesome!

2023-03-15 16:57 UTC, cmastr approved these changes

2023-03-15 16:58 UTC, msdolbey approved these changes
👍 
Meant to approve earlier, but NOW I'LL ACTUALLY DO IT, instead of leaving it as a comment like a yokel. 
![Looks great](https://y.yarn.co/b2e94968-fed6-4134-bad5-798930617659_text.gif)

2023-03-15 16:59 UTC, tillt commented
Ready to merge -- giving it a final glance....

2023-03-15 17:55 UTC, jimmidyson approved these changes

2023-03-15 17:55 UTC, merged